<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>bug-report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="bug-report_files/libs/clipboard/clipboard.min.js"></script>
<script src="bug-report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="bug-report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="bug-report_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="bug-report_files/libs/quarto-html/popper.min.js"></script>
<script src="bug-report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="bug-report_files/libs/quarto-html/anchor.min.js"></script>
<link href="bug-report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="bug-report_files/libs/quarto-html/quarto-syntax-highlighting-1fe81d0376b2c50856e68e651e390326.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="bug-report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="bug-report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="bug-report_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="bug-report-gcta-reml-fails-to-converge-in-gwas-analysis" class="level1">
<h1>Bug Report: GCTA-REML fails to converge in GWAS analysis</h1>
<section id="description" class="level2">
<h2 class="anchored" data-anchor-id="description">Description</h2>
<p>Several process failures for two NF processes <code>GCTA_MAKE GRM</code> and <code>GCTA_PERFORM_GWA</code></p>
<p>Pipeline failed after reaching the max number of errors for the <code>GCTA_PERFORM_GWA</code> process for a particular input parameter combination. The error message indicates that the fastGWA-REML method used in GCTA is unable to converge for the given data and parameters.</p>
</section>
<section id="command-used" class="level2">
<h2 class="anchored" data-anchor-id="command-used">Command Used</h2>
<p><em>(rockfish production run; full command not captured — add from .nextflow.log)</em></p>
</section>
<section id="error-output" class="level2">
<h2 class="anchored" data-anchor-id="error-output">Error output</h2>
<section id="execution-summary" class="level3">
<h3 class="anchored" data-anchor-id="execution-summary">Execution Summary</h3>
<pre><code>[e9/5c2619] Submitted process &gt; GCTA_PERFORM_GWA (5 48 0.8 gamma inbred nopca ce.n300.r24_0.05)                                                                                                                                
executor &gt;  local (251), slurm (58236)                                                                                                                                                                                         
[be/d0c7c4] LOCAL_GET_CONTIG_INFO (ce.n100.r01)                                      [100%] 1 of 1 ✔                                                                                                                           
[c8/2bc47a] BCFTOOLS_EXTRACT_STRAINS (ce.n500.r20)                                   [100%] 250 of 250 ✔                                                                                                                       
[1b/7342d4] BCFTOOLS_RENAME_CHROMS (ce.n500.r13)                                     [100%] 250 of 250 ✔                                                                                                                       
[62/581265] PLINK_RECODE_MS_VCF (ce.n500.r20_0.05)                                   [100%] 250 of 250 ✔                                                                                                                       
[e4/579828] PLINK_RECODE_CV_VCF (ce.n500.r20_0.05)                                   [100%] 250 of 250 ✔                                                                                                                       
[95/91729b] BCFTOOLS_CREATE_GENOTYPE_MATRIX (ce.n500.r37_0.05)                       [100%] 250 of 250 ✔                                                                                                                       
[89/250b3a] R_FIND_GENOTYPE_MATRIX_EIGEN (2 ce.n500.r29_0.05)                        [100%] 1500 of 1500 ✔                                                                                                                     
[62/bb3d7e] LOCAL_COMPILE_EIGENS (ce.n500.r20 0.05)                                  [100%] 250 of 250 ✔                                                                                                                       
[11/73ace9] PYTHON_SIMULATE_EFFECTS_GLOBAL (5 28 gammace.n100.r17_0.05)              [100%] 12500 of 12500 ✔                                                                                                                   
[01/fbef31] GCTA_SIMULATE_PHENOTYPES (5 32 0.8 gamma ce.n300.r29_0.05)               [ 85%] 10700 of 12500                                                                                                                     
[c9/96f4ed] PLINK_UPDATE_BY_H2 (5 31 0.8 gamma ce.n200.r50_0.05)                     [ 62%] 6700 of 10700                                                                                                                      
[09/1fbb04] GCTA_MAKE_GRM (5 19 0.8 gamma inbred ce.n100.r37_0.05)                   [ 57%] 7702 of 13404, failed: 4, retries: 4                                                                                               
[fc/cb0551] GCTA_PERFORM_GWA (5 48 0.8 gamma inbred pca ce.n300.r24_0.05)            [ 48%] 7202 of 14804, failed: 5, retries: 4                                                                                               
[b9/7727d7] DB_MIGRATION_WRITE_MARKER_SET (ce.n100.r19_0.05)                         [100%] 250 of 250 ✔                                                                                                                       
[b5/c22e9c] DB_MIGRATION_WRITE_GENOTYPE_MATRIX (ce.n500.r34_0.05)                    [100%] 250 of 250 ✔                                                                                                                       
[3a/3e1b3b] DB_MIGRATION_WRITE_TRAIT_DATA (ce.n100.r41_5_36_0.8)                     [ 71%] 7600 of 10700                                                                                                                      
[33/f97ca8] DB_MIGRATION_WRITE_GWA_TO_DB (5 7 0.8 gamma loco nopca ce.n300.r18_0.05) [ 32%] 2300 of 7000                                                                                                                       
[-        ] DB_MIGRATION_AGGREGATE_METADATA                                          -                                                                                                                                         
[-        ] DB_MIGRATION_ANALYZE_QTL                                                 -                                                                                                                                         
[-        ] DB_MIGRATION_ASSESS_SIMS                                                 -                                                                                                                                        </code></pre>
</section>
<section id="caused-by" class="level3">
<h3 class="anchored" data-anchor-id="caused-by">Caused by</h3>
<pre><code>  Process `GCTA_PERFORM_GWA (5 32 0.8 gamma inbred nopca ce.n100.r06_0.05)` terminated with an error exit status (1)</code></pre>
</section>
<section id="command-output" class="level3">
<h3 class="anchored" data-anchor-id="command-output">Command output:</h3>
<pre><code>  Overall computational time: 0.05 sec.
  *******************************************************************
  * Genome-wide Complex Trait Analysis (GCTA)
  * version v1.94.1 Linux
  * Built at Nov 15 2022 21:14:25, by GCC 8.5
  * (C) 2010-present, Yang Lab, Westlake University
  * Please report bugs to Jian Yang &lt;jian.yang@westlake.edu.cn&gt;
  *******************************************************************
  Analysis started at 17:25:12 EDT on Wed Apr 22 2026.
  Hostname: c618

  Options:

  --fastGWA-mlm-exact
  --bfile TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06
  --grm-sparse 5_32_0.8_0.05_gamma_ce.n100.r06_sparse_grm_inbred
  --out 5_32_0.8_0.05_gamma_ce.n100.r06_lmm-exact_inbred_nopca
  --pheno 5_32_0.8_0.05_gamma_ce.n100.r06_sims.pheno
  --extract plink_snplist.txt
  --thread-num 1

  The program will be running with up to 1 threads.
  Reading PLINK FAM file from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06.fam]...
  100 individuals to be included from FAM file.
  Reading phenotype data from [5_32_0.8_0.05_gamma_ce.n100.r06_sims.pheno]...
  100 overlapping individuals with non-missing data to be included from the phenotype file.
  100 individuals to be included. 0 males, 0 females, 100 unknown.
  Reading PLINK BIM file from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06.bim]...
  38597 SNPs to be included from BIM file(s).
  Get 38597 SNPs from list [plink_snplist.txt].
  After extracting SNP, 38597 SNPs remain.
  Reading the sparse GRM file from [5_32_0.8_0.05_gamma_ce.n100.r06_sparse_grm_inbred]...
  After matching all the files, 100 individuals to be included in the analysis.
  Estimating the genetic variance (Vg) by fastGWA-REML (grid search)...
  Iteration 1, step size: 1.8458, logL: -245.408. Vg: 114.44, searching range: 112.594 to 116.286
  Iteration 2, step size: 0.246107, logL: -244.137. Vg: 115.547, searching range: 115.301 to 115.793
  Iteration 3, step size: 0.0328143, logL: -243.816. Vg: 115.629, searching range: 115.596 to 115.662
  Iteration 4, step size: 0.00437524, logL: -243.764. Vg: 115.649, searching range: 115.645 to 115.653
  Iteration 5, step size: 0.000583365, logL: -243.764. Vg: 115.648, searching range: 115.647 to 115.648
  Iteration 6, step size: 7.7782e-05, logL: -243.764. Vg: 115.648, searching range: 115.647 to 115.648
  Iteration 7, step size: 1.03709e-05, logL: -243.764. Vg: 115.648, searching range: 115.648 to 115.648
  Iteration 8, step size: 1.38279e-06, logL: -243.764. Vg: 115.648, searching range: 115.648 to 115.648
  Iteration 9, step size: 1.84372e-07, logL: -243.764. Vg: 115.648, searching range: 115.648 to 115.648
  Iteration 10, step size: 2.45829e-08, logL: -243.764. Vg: 115.648, searching range: 115.648 to 115.648
  Iteration 11, step size: 3.27773e-09, logL: -243.764. Vg: 115.648, searching range: 115.648 to 115.648
  Iteration 12, step size: 4.3703e-10, logL: -243.764. Vg: 115.648, searching range: 115.648 to 115.648
  Iteration 13, step size: 5.82702e-11, logL: -243.764. Vg: 115.648, searching range: 115.648 to 115.648
  Best guess Vg range: 115.647573108802 to 115.647573108919, Vp: 115.362665270647
  Error: fastGWA-REML can't converge.</code></pre>
</section>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis</h2>
<section id="error-classification" class="level3">
<h3 class="anchored" data-anchor-id="error-classification">Error classification</h3>
<p>This is a <strong>different failure mode from issue #143</strong>. Issue #143 was <code>"the Vp is below 1e-5"</code> (phenotype variance too small for GCTA’s internal threshold, fixed by iterative Vp scaling in <code>GCTA_MAKE_GRM</code>). The current error is <code>"fastGWA-REML can't converge"</code>.</p>
</section>
<section id="root-cause-vg-vp-h²-1" class="level3">
<h3 class="anchored" data-anchor-id="root-cause-vg-vp-h²-1">Root cause: Vg &gt; Vp (h² &gt; 1)</h3>
<p>The GCTA log reveals the underlying condition:</p>
<pre><code>Best guess Vg range: 115.647573..., Vp: 115.362665...</code></pre>
<p><strong>Vg (115.648) &gt; Vp (115.363)</strong> — the REML grid search converges numerically (step size reaches ~6e-11 by iteration 13) but the MLE solution has estimated genetic variance exceeding total phenotypic variance, implying h² ≈ 1.0025. Since h² must lie in [0, 1], the solution is outside the valid parameter space. GCTA detects this and hard-fails rather than clamping to the boundary (h² = 1).</p>
</section>
<section id="mechanism-sparse-grm-distortion" class="level3">
<h3 class="anchored" data-anchor-id="mechanism-sparse-grm-distortion">Mechanism: sparse GRM distortion</h3>
<p>The failure chain is:</p>
<ol type="1">
<li><code>GCTA_MAKE_GRM</code> builds the full dense GRM and runs an iterative REML loop, scaling phenotype until full-GRM Vp ≥ 1e-4. This passes — Vp = 115.363 is large.</li>
<li><code>GCTA_PERFORM_GWA</code> (inbred mode) sparsifies the GRM with <code>--make-bK-sparse 0.05</code>, zeroing all relatedness entries below 0.05.</li>
<li><code>--fastGWA-mlm-exact</code> then estimates Vg against the <strong>sparse</strong> GRM structure. For small, highly inbred <em>C. elegans</em> populations (n=100), sparsification changes the eigenstructure enough that the sparse-GRM MLE for Vg exceeds Vp.</li>
<li>GCTA reports “can’t converge” because h² &gt; 1.</li>
</ol>
<p>Parameters in the failing task confirm the at-risk profile: <code>nqtl=5 rep=32 h2=0.8 inbred nopca ce.n100.r06 maf=0.05</code> — small sample size (n=100), high simulated heritability (0.8), inbred mode.</p>
</section>
<section id="why-the-existing-fix-and-planned-safety-net-do-not-cover-this" class="level3">
<h3 class="anchored" data-anchor-id="why-the-existing-fix-and-planned-safety-net-do-not-cover-this">Why the existing fix and planned safety net do not cover this</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Issue #143 fix</th>
<th>Planned safety net (<code>future-gwa-safety-net.md</code>)</th>
<th>This bug</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Error message</td>
<td><code>"the Vp is below 1e-5"</code></td>
<td><code>"the Vp is below 1e-5"</code> (grep target)</td>
<td><code>"fastGWA-REML can't converge"</code></td>
</tr>
<tr class="even">
<td>Condition</td>
<td>Vp &lt; 1e-5 (absolute)</td>
<td>Vp &lt; 1e-5 (absolute)</td>
<td>Vg &gt; Vp (ratio, h² &gt; 1)</td>
</tr>
<tr class="odd">
<td>Fix approach</td>
<td>Scale pheno ×1000</td>
<td>Scale pheno ×1000 + retry</td>
<td>Scaling is ineffective — the ratio Vg/Vp is scale-invariant</td>
</tr>
</tbody>
</table>
<p>Specifically: the grep in the planned safety net (<code>grep -q "the Vp is below 1e-5"</code>) would not match <code>"fastGWA-REML can't converge"</code>, so the <code>else</code> branch would fire and immediately <code>exit \${GWA_EXIT}</code> — no benefit.</p>
<p>And even if the grep were extended to match this error, scaling the phenotype would not help: multiplying all phenotype values by k scales both Vg and Vp by k², leaving h² = Vg/Vp unchanged.</p>
</section>
<section id="retry-behavior" class="level3">
<h3 class="anchored" data-anchor-id="retry-behavior">Retry behavior</h3>
<p>The execution summary shows <code>failed: 4, retries: 4</code> for <code>GCTA_MAKE_GRM</code> and <code>failed: 5, retries: 4</code> for <code>GCTA_PERFORM_GWA</code>. The <code>rockfish.config</code> <code>maxRetries = 3</code> setting was designed for transient SLURM failures. This GCTA convergence failure is <strong>deterministic</strong> — the same phenotype with the same sparse GRM will always fail. All retries are wasted compute.</p>
<hr>
</section>
</section>
<section id="debugging-steps" class="level2">
<h2 class="anchored" data-anchor-id="debugging-steps">Debugging steps</h2>
<p>The following commands should be run from the pipeline launch directory on the cluster (where <code>.nextflow.log</code> and the <code>nextflow</code> binary are available). Use <code>nextflow log</code> to retrieve specific task work directories — do not search scratch space broadly.</p>
<section id="step-0-identify-the-run-name" class="level3">
<h3 class="anchored" data-anchor-id="step-0-identify-the-run-name">Step 0: Identify the run name</h3>
<p>Activate the conda environment used for the run to ensure <code>nextflow</code> is available</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> activate /data/eande106/software/conda_envs/nf24_env</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="ex">nextflow</span> log</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>2026-04-22 12:51:50     4h 38m 23s      spontaneous_swirles     ERR     04477aefd0      39a52330-c538-40ee-9c9d-b13ea7d406be    nextflow run main.nf -profile rockfish --strainfile data/sims_panelsize_ce-cb-ct_nqtl5_h2-0.8_50reps/strains_panelsize_ce.tsv --nqtl data/sims_panelsize_ce-cb-ct_nqtl5_h2-0.8_50reps/nqtl.csv --h2 data/sims_panelsize_ce-cb-ct_nqtl5_h2-0.8_50reps/h2.csv --effect data/sims_panelsize_ce-cb-ct_nqtl5_h2-0.8_50reps/effect_sizes.csv --reps 50 --cv_maf 0.05 --cv_ld 0.8 --output_dir Sims_panelsize_ce_nqtl5_h2-0.8_50reps -work-dir /scratch4/eande106/Ryan_tmp/nf-work-panelsize</code></pre>
<p>The run name is <code>spontaneous_swirles</code>. ### Step 1: Confirm the error is deterministic across retries</p>
<p>Retrieve all failed <code>GCTA_PERFORM_GWA</code> task work directories and check that every attempt shows the same convergence failure (not a SLURM OOM or timeout):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="ex">nextflow</span> log spontaneous_swirles <span class="dt">\</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">-filter</span> <span class="st">'process == "GCTA_PERFORM_GWA" &amp;&amp; status == "FAILED"'</span> <span class="dt">\</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">-f</span> name,workdir,exit,attempt <span class="dt">\</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="kw">|</span> <span class="fu">head</span> <span class="at">-40</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>GCTA_PERFORM_GWA (5 32 0.8 gamma inbred nopca ce.n100.r06_0.05) /scratch4/eande106/Ryan_tmp/nf-work-panelsize/f3/747893c194d638e6a37318ff11f5d4 1       1
GCTA_PERFORM_GWA (5 32 0.8 gamma inbred nopca ce.n100.r06_0.05) /scratch4/eande106/Ryan_tmp/nf-work-panelsize/9b/29062ca47de46d427a0d1b5a72be8c 1       2
GCTA_PERFORM_GWA (5 32 0.8 gamma inbred nopca ce.n100.r06_0.05) /scratch4/eande106/Ryan_tmp/nf-work-panelsize/9b/a1a1c1301ffef5b06d739e5d0c35c3 1       3
GCTA_PERFORM_GWA (5 32 0.8 gamma inbred pca ce.n100.r06_0.05)   /scratch4/eande106/Ryan_tmp/nf-work-panelsize/70/cebf607bfd422b62fe128015d5591e 1       1
GCTA_PERFORM_GWA (5 32 0.8 gamma inbred nopca ce.n100.r06_0.05) /scratch4/eande106/Ryan_tmp/nf-work-panelsize/91/5765b40e98558fb17f709f97d61486 1       4</code></pre>
<p>Check each failed task’s <code>.command.out</code> by iterating over the <code>nextflow log</code> output above:</p>
<p>The loop:</p>
<ol type="1">
<li>Re-runs the same nextflow log query.</li>
<li>Reads each output line.</li>
<li>Extracts the workdir field using awk from the end of the line.</li>
<li>Greps the exact convergence error string from each <code>.command.out</code></li>
</ol>
<p>Lets check the files as well, since the GCTA output may be there instead</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="ex">nextflow</span> log spontaneous_swirles <span class="dt">\</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">-filter</span> <span class="st">'process == "GCTA_PERFORM_GWA" &amp;&amp; status == "FAILED"'</span> <span class="dt">\</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">-f</span> name,workdir,exit,attempt <span class="dt">\</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="kw">|</span> <span class="fu">head</span> <span class="at">-40</span> <span class="dt">\</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="kw">|</span> <span class="cf">while</span> <span class="va">IFS</span><span class="op">=</span> <span class="bu">read</span> <span class="at">-r</span> <span class="va">line</span><span class="kw">;</span> <span class="cf">do</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>      <span class="va">workdir</span><span class="op">=</span><span class="st">"</span><span class="va">$(</span><span class="fu">awk</span> <span class="st">'{print $(NF-2)}'</span> <span class="op">&lt;&lt;&lt;</span> <span class="st">"</span><span class="va">$line</span><span class="st">"</span><span class="va">)</span><span class="st">"</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>      <span class="bu">echo</span> <span class="st">"=== </span><span class="va">$workdir</span><span class="st"> ==="</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grep</span> <span class="at">-F</span> <span class="st">"Error: fastGWA-REML can't converge."</span> <span class="st">"</span><span class="va">$workdir</span><span class="st">/.command.out"</span> <span class="kw">||</span> <span class="fu">true</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>      <span class="bu">echo</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">done</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>=== /scratch4/eande106/Ryan_tmp/nf-work-panelsize/f3/747893c194d638e6a37318ff11f5d4 ===
Error: fastGWA-REML can't converge.

=== /scratch4/eande106/Ryan_tmp/nf-work-panelsize/9b/29062ca47de46d427a0d1b5a72be8c ===
Error: fastGWA-REML can't converge.

=== /scratch4/eande106/Ryan_tmp/nf-work-panelsize/9b/a1a1c1301ffef5b06d739e5d0c35c3 ===
Error: fastGWA-REML can't converge.

=== /scratch4/eande106/Ryan_tmp/nf-work-panelsize/70/cebf607bfd422b62fe128015d5591e ===
Error: fastGWA-REML can't converge.

=== /scratch4/eande106/Ryan_tmp/nf-work-panelsize/91/5765b40e98558fb17f709f97d61486 ===
Error: fastGWA-REML can't converge.</code></pre>
<p>Every retry attempt shows <code>"fastGWA-REML can't converge"</code> and the failure is deterministic.</p>
</section>
<section id="step-2-confirm-the-corresponding-gcta_make_grm-completed-with-vp-well-above-threshold" class="level3">
<h3 class="anchored" data-anchor-id="step-2-confirm-the-corresponding-gcta_make_grm-completed-with-vp-well-above-threshold">Step 2: Confirm the corresponding GCTA_MAKE_GRM completed with Vp well above threshold</h3>
<p>For the same parameter combination (<code>5 32 0.8 gamma inbred ce.n100.r06_0.05</code>), find the matching <code>GCTA_MAKE_GRM</code> work directory and inspect its REML output:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="ex">nextflow</span> log spontaneous_swirles <span class="dt">\</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">-filter</span> <span class="st">'process == "GCTA_MAKE_GRM" &amp;&amp; tag == "5 32 0.8 gamma inbred ce.n100.r06_0.05"'</span> <span class="dt">\</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">-f</span> tag,workdir,status</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Output:</p>
<pre><code>5 32 0.8 gamma inbred ce.n100.r06_0.05  /scratch4/eande106/Ryan_tmp/nf-work-panelsize/d2/0fddf7b2eec655177227293c460c5e COMPLETED</code></pre>
<p>Now check the <code>check_vp.hsq</code> file in that work directory, which contains the REML estimates from <code>GCTA_MAKE_GRM</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> /scratch4/eande106/Ryan_tmp/nf-work-panelsize/d2/0fddf7b2eec655177227293c460c5e/check_vp.hsq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Output:</p>
<pre><code>Source  Variance        SE
V(G)    107.446470      16.102063
V(e)    0.000115        1.189889
Vp      107.446585      15.850732
V(G)/Vp 0.999999        0.011074
logL    -246.057
logL0   -286.833
LRT     81.551
df      1
Pval    0.0000e+00
n       100</code></pre>
<p>E<code>GCTA_MAKE_GRM</code> completed successfully and <code>check_vp.hsq</code> shows Vp well above 1e-4 (e.g.&nbsp;Vp = 107.446585). This rules out the issue #143 Vp-too-small failure mode and confirms the two errors are distinct. The <code>GCTA_MAKE_GRM</code> REML converged to a valid solution with h² ≈ 1, but the <code>GCTA_PERFORM_GWA</code> REML with the sparse GRM fails to converge because it finds an invalid solution with h² &gt; 1.</p>
<section id="step-2a-check-if-the-guard-against-issue-143-is-working-as-intended-for-this-parameter-combination" class="level4">
<h4 class="anchored" data-anchor-id="step-2a-check-if-the-guard-against-issue-143-is-working-as-intended-for-this-parameter-combination">Step 2a: Check if the guard against issue #143 is working as intended for this parameter combination</h4>
<p>Check the <code>GCTA_MAKE_GRM</code> logs for this parameter combination to confirm that the Vp scaling loop is working as intended (it should not have triggered since Vp was already large):</p>
<p>Check the <code>.command.out</code> for the <code>GCTA_MAKE_GRM</code> task for this parameter combination:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> /scratch4/eande106/Ryan_tmp/nf-work-panelsize/d2/0fddf7b2eec655177227293c460c5e/.command.out</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Output:</p>
<pre><code>*******************************************************************
* Genome-wide Complex Trait Analysis (GCTA)
* version v1.94.1 Linux
* Built at Nov 15 2022 21:14:25, by GCC 8.5
* (C) 2010-present, Yang Lab, Westlake University
* Please report bugs to Jian Yang &lt;jian.yang@westlake.edu.cn&gt;
*******************************************************************
Analysis started at 15:28:05 EDT on Wed Apr 22 2026.
Hostname: c640

Accepted options:
--bfile TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06
--autosome
--extract plink_snplist.txt
--make-grm-inbred
--out TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06_gcta_grm_inbred
--thread-num 1

Note: This is a multi-thread program. You could specify the number of threads by the --thread-num option to speed up the computation if there are multiple processors in your machine.

Reading PLINK FAM file from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06.fam].
100 individuals to be included from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06.fam].
Reading PLINK BIM file from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06.bim].
38597 SNPs to be included from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06.bim].
Reading a list of SNPs from [plink_snplist.txt].
38597 SNPs are extracted from [plink_snplist.txt].
38597 SNPs from chromosome 1 to chromosome 22 are included in the analysis.
Reading PLINK BED file from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06.bed] in SNP-major format ...
Genotype data for 100 individuals and 38597 SNPs to be included from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06.bed].
Calculating allele frequencies ...
Recoding genotypes (individual major mode) ...

Calculating the genetic relationship matrix (GRM) ... (Note: default speed-optimized mode, may use huge RAM)

Summary of the GRM:
Mean of diagonals = 2
Variance of diagonals = 1.11747
Mean of off-diagonals = -0.0202019
Variance of off-diagonals = 0.220803
GRM of 100 individuals has been saved in the file [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06_gcta_grm_inbred.grm.bin] (in binary format).
Number of SNPs to calculate the genetic relationship between each pair of individuals has been saved in the file [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06_gcta_grm_inbred.grm.N.bin] (in binary format).
IDs for the GRM file [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06_gcta_grm_inbred.grm.bin] have been saved in the file [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06_gcta_grm_inbred.grm.id].

Analysis finished at 15:28:06 EDT on Wed Apr 22 2026
Overall computational time: 0.26 sec.
*******************************************************************
* Genome-wide Complex Trait Analysis (GCTA)
* version v1.94.1 Linux
* Built at Nov 15 2022 21:14:25, by GCC 8.5
* (C) 2010-present, Yang Lab, Westlake University
* Please report bugs to Jian Yang &lt;jian.yang@westlake.edu.cn&gt;
*******************************************************************
Analysis started at 15:28:06 EDT on Wed Apr 22 2026.
Hostname: c640

Accepted options:
--grm TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06_gcta_grm_inbred
--pheno working_pheno.txt
--reml
--out check_vp
--thread-num 1

Note: This is a multi-thread program. You could specify the number of threads by the --thread-num option to speed up the computation if there are multiple processors in your machine.

Reading IDs of the GRM from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06_gcta_grm_inbred.grm.id].
100 IDs are read from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06_gcta_grm_inbred.grm.id].
Reading the GRM from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06_gcta_grm_inbred.grm.bin].
GRM for 100 individuals are included from [TO_SIMS_5_32_0.8_0.05_gamma_ce.n100.r06_gcta_grm_inbred.grm.bin].
Reading phenotypes from [working_pheno.txt].
Non-missing phenotypes of 100 individuals are included from [working_pheno.txt].

100 individuals are in common in these files.

Performing  REML analysis ... (Note: may take hours depending on sample size).
100 observations, 1 fixed effect(s), and 2 variance component(s)(including residual variance).
Calculating prior values of variance components by EM-REML ...
Updated prior values: 53.7589 39.5189
logL: -258.533
Running AI-REML algorithm ...
Iter.   logL    V(G)    V(e)
1       -253.48 67.24130        22.01094
2       -249.66 76.49509        14.18447
3       -248.39 83.21566        9.63918
4       -247.81 88.59034        6.55820
5       -247.47 102.95575       0.00012 (1 component(s) constrained)
6       -246.01 107.25889       0.00012 (1 component(s) constrained)
7       -246.05 107.31806       0.00012 (1 component(s) constrained)
8       -246.05 107.44632       0.00012 (1 component(s) constrained)
9       -246.06 107.44647       0.00012 (1 component(s) constrained)
Log-likelihood ratio converged.

Calculating the logLikelihood for the reduced model ...
(variance component 1 is dropped from the model)
Calculating prior values of variance components by EM-REML ...
Updated prior values: 115.36267
logL: -286.83258
Running AI-REML algorithm ...
Iter.   logL    V(e)
1       -286.83 115.36267
Log-likelihood ratio converged.

Summary result of REML analysis:
Source  Variance        SE
V(G)    107.446470      16.102063
V(e)    0.000115        1.189889
Vp      107.446585      15.850732
V(G)/Vp 0.999999        0.011074

Sampling variance/covariance of the estimates of variance components:
2.592764e+02    -4.723275e+00
-4.723275e+00   1.415835e+00

Summary result of REML analysis has been saved in the file [check_vp.hsq].

Analysis finished at 15:28:06 EDT on Wed Apr 22 2026
Overall computational time: 0.02 sec.
Vp=107.446585 &gt;= 0.0001 at round 1; done</code></pre>
<p>It looks like no Vp scaling iterations were triggered, which is expected since Vp was already large. This confirms that the issue #143 guard is working as intended and that this convergence failure is a distinct issue.</p>
<p><strong>However:</strong> The REML analysis identies the same h² ≈ 1 solution (V(G)/Vp = 0.999999) as the <code>GCTA_PERFORM_GWA</code> REML</p>
</section>
</section>
<section id="step-3-characterize-which-parameter-combinations-fail" class="level3">
<h3 class="anchored" data-anchor-id="step-3-characterize-which-parameter-combinations-fail">Step 3: Characterize which parameter combinations fail</h3>
<p>Check whether failures are concentrated in small-n, high-h² inbred tasks (and absent from loco tasks with the same parameters):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># All GCTA_PERFORM_GWA failures with their task names</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="ex">nextflow</span> log spontaneous_swirles <span class="dt">\</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">-filter</span> <span class="st">'process == "GCTA_PERFORM_GWA" &amp;&amp; status == "FAILED"'</span> <span class="dt">\</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">-f</span> name <span class="dt">\</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="kw">|</span> <span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span> <span class="kw">|</span> <span class="fu">sort</span> <span class="at">-rn</span> <span class="kw">|</span> <span class="fu">head</span> <span class="at">-40</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Output:</p>
<pre><code>4 GCTA_PERFORM_GWA (5 32 0.8 gamma inbred nopca ce.n100.r06_0.05)
1 GCTA_PERFORM_GWA (5 32 0.8 gamma inbred pca ce.n100.r06_0.05)</code></pre>
</section>
</section>
</section>
<section id="check-if-any-loco-mode-tasks-failed-with-the-same-error" class="level1">
<h1>Check if any loco-mode tasks failed with the same error</h1>
<pre><code>nextflow log &lt;run&gt; \
  -filter 'process == "GCTA_PERFORM_GWA" &amp;&amp; status == "FAILED"' \
  -f name \
  | grep "loco"</code></pre>
<p>Expected: failures are exclusively in <code>inbred</code> mode (never <code>loco</code>) and enriched in small strain-set groups (ce.n100) and/or high h² (0.8). Absence of <code>loco</code> failures would confirm the sparse-GRM distortion hypothesis, since loco mode uses the full GRM and cannot produce this error.</p>
<hr>
<section id="proposed-fix-direction" class="level2">
<h2 class="anchored" data-anchor-id="proposed-fix-direction">Proposed fix direction</h2>
<p>The fix must handle the case where <code>--fastGWA-mlm-exact</code> with <code>--grm-sparse</code> converges to h² &gt; 1. Two options:</p>
<p><strong>Option A — Graceful skip with empty output (preferred):</strong> When GCTA fails with <code>"fastGWA-REML can't converge"</code>, write a header-only <code>.fastGWA</code> file and exit 0. Downstream <code>DB_MIGRATION_WRITE_GWA_TO_DB</code> would ingest an empty mapping — zero association statistics for this trait. The pipeline continues; downstream QTL assessment simply finds no QTL for this replicate.</p>
<p><strong>Option B — Extend the planned safety net:</strong> Extend the <code>future-gwa-safety-net.md</code> grep to also match <code>"fastGWA-REML can't converge"</code> but respond with a graceful skip (write empty output) rather than a scale-and-retry loop, since scaling cannot fix h² &gt; 1.</p>
<p>Option A is simpler; Option B integrates cleanly with the existing safety net plan. Both require verifying that <code>DB_MIGRATION_WRITE_GWA_TO_DB</code> handles an empty (header-only) <code>.fastGWA</code> file without crashing.</p>
<p><em>Pending debugging step results before implementing.</em></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>